apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: elasticsearch  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: elasticsearch  
  template:  
    metadata:  
      labels:  
        app: elasticsearch  
    spec:  
      containers:  
      - name: elasticsearch  
        image: elasticsearch:7.17.0  
        ports:  
        - containerPort: 9200  
        env:  
        - name: discovery.type  
          value: single-node  

---  
apiVersion: v1  
kind: Service  
metadata:  
  name: elasticsearch  
spec:  
  ports:  
  - port: 9200  
    targetPort: 9200  
  selector:  
    app: elasticsearch  

---  
apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: flask-app  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: flask-app  
  template:  
    metadata:  
      labels:  
        app: flask-app  
    spec:  
      containers:  
      - name: flask-app  
        image: <your_dockerhub_username>/flask-elasticsearch-demo:latest  
        ports:  
        - containerPort: 5000  
        env:  
        - name: ELASTICSEARCH_URL  
          value: "http://elasticsearch:9200"  

---  
apiVersion: v1  
kind: Service  
metadata:  
  name: flask-app  
spec:  
  ports:  
  - port: 5000  
    targetPort: 5000  
  selector:  
    app: flask-app
